\documentclass[11pt]{article}

%% This document source is based on the excellent:
%% http://www.math.smith.edu/~nhorton/sleuth/
%%
%% Specifically, 
%% http://www.math.smith.edu/~nhorton/sleuth/chapter02.Rnw

\usepackage{natbib}
\usepackage[margin=1in,bottom=.5in,includehead,includefoot]{geometry}
\usepackage{hyperref}
\usepackage{language}
\usepackage{alltt}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}

%% Now begin customising things. See the fancyhdr docs for more info.

\chead{}
\lhead[\sf \thepage]{\sf \leftmark}
\rhead[\sf \leftmark]{\sf \thepage}
\lfoot{}
\cfoot{Independent contrasts}
\rfoot{}

\newcounter{myenumi}
\newcommand{\saveenumi}{\setcounter{myenumi}{\value{enumi}}}
\newcommand{\reuseenumi}{\setcounter{enumi}{\value{myenumi}}}

\pagestyle{fancy}

\def\R{{\sf R}}
\def\Rstudio{{\sf RStudio}}
\def\RStudio{{\sf RStudio}}
\def\term#1{\textbf{#1}}
\def\tab#1{{\sf #1}}


\usepackage{relsize}

\newlength{\tempfmlength}
\newsavebox{\fmbox}
\newenvironment{fmpage}[1]
     {
   \medskip
   \setlength{\tempfmlength}{#1}
   \begin{lrbox}{\fmbox}
     \begin{minipage}{#1}
     \vspace*{.02\tempfmlength}
		 \hfill
	   \begin{minipage}{.95 \tempfmlength}}
		 {\end{minipage}\hfill
		 \vspace*{.015\tempfmlength}
		 \end{minipage}\end{lrbox}\fbox{\usebox{\fmbox}}
	 \medskip
	 }


\newenvironment{boxedText}[1][.98\textwidth]%
{%
\begin{center}
\begin{fmpage}{#1}
}%
{%
\end{fmpage}
\end{center}
}

\newenvironment{boxedTable}[2][tbp]%
{%
\begin{table}[#1]
  \refstepcounter{table}
  \begin{center}
\begin{fmpage}{.98\textwidth}
  \begin{center}
	\sf \large Box~\expandafter\thetable. #2
\end{center}
\medskip
}%
{%
\end{fmpage}
\end{center}
\end{table}		% need to do something about exercises that follow boxedTable
}


\newcommand{\cran}{\href{http://www.R-project.org/}{CRAN}}

\title{Phylogenetic Independent Contrasts in R}

\author{
Casey Dunn}

\date{\today}

<<echo=FALSE>>=
options(width=70)
@



\begin{document}


\maketitle
\tableofcontents

%\parindent=0pt


\SweaveOpts{
  	dev="pdf",
	fig.path="figures/",
	prompt=FALSE,   
	comment="#"    # turn off commenting of ouput (but perhaps we should not do this either
	}

<<setup,echo=FALSE,message=FALSE>>=
showOriginal=FALSE
showNew=TRUE
@ 

\section{Introduction}

This document introduces you to a variety of tools and approaches to analyzing 
phylogenetic data with R.

There is detailed information on phylogenetic analysis with R at both 
\href{http://www.r-phylo.org/wiki/Main_Page}{the R phylo wiki} and the 
\href{http://cran.r-project.org/web/views/Phylogenetics.html}{CRAN task page for phylogenetics}.
Also consult the excellent book by \cite{Paradis:2012wn}.

Make sure that you have the most recent version of R installed. For the 
analyses below, you will need to install the following libraries in R:

\begin{itemize}
\item ape
\item geiger
\item phylobase
\end{itemize}

Update them if they are not the latest version.

\section{Simulating trees}

First, load ape:

<<>>=
library(ape)
@

The simplest way to generate a random tree is with the rcoal() function:

<<>>=
t <- rcoal( 8 )
plot( t )
@

The only required argument is the number of taxa. rcoal() generates ultrametric 
trees, the related function rtree() can be used to generate trees whose tips 
are not contemporaneous.


\section{Simulating phenotypic data on trees}

The sim.char() function from the geiger library is a convenient tool for 
simulating character evolution. 

We'll simulate two characters, each with a variance of 1 and a covariance with 
each other of 0.3. First, make a variance-covariance matrix describes this 
relationship:

<<>>=
vcv <- c( 1, 0.3, 0.3, 1 )
dim( vcv ) <- c( 2, 2 )
vcv
@

Now, generate 500 simulated datasets on tree t according to vcv:


<<>>=
library(geiger)
xy <- sim.char( t, vcv, nsims = 500, model = "brownian", root.state = 1 )
xy[,,1]
@

This shows just the first simulation.

You can plot the data right onto the tree. The phylobase library has some nice 
tools for plotting miltivariate data:


<<>>=
library( adephylo )
xy4d <- phylo4d( t, xy[,,1] )
table.phylo4d( xy4d, box=FALSE )

@



\section{How this document was made}
This document is a computable data report compiled directly from the data. 
To recreate this file from the data, you will need to install:

\begin{itemize}
  \item R (\url{http://www.r-project.org}). This document was generated with 
  version 2.15.2.
  \item The R package knitr (\url{http://yihui.name/knitr/}), which can be 
  installed from within R. This document was generated with version 0.9.
  \item pdflatex, which comes with LaTeX distributions 
  (\url{http://www.latex-project.org/ftp.html}). This document was generated 
  with version 3.1415926-2.4-1.40.13.
\end{itemize}

From within the knitr directory, launch R and run:

<<eval=FALSE>>=
library(knitr)
knit("comparative_r.Rnw")
quit()
@

This will generate a new tex file. To compile this tex file into a pdf 
file, run the following at the shell command line:

<<eval=FALSE, prompt=FALSE>>=
pdflatex comparative_r.tex
@

In addition to recreating this document as-is, you can directly edit and add to 
the analyses in the .Rnw source file. You can also copy the R source code from 
the .Rnw file.

\bibliographystyle{amnat}

\bibliography{references}


\end{document}
