\documentclass[11pt]{article}

%% This document source is based on the excellent:
%% http://www.math.smith.edu/~nhorton/sleuth/
%%
%% Specifically, 
%% http://www.math.smith.edu/~nhorton/sleuth/chapter02.Rnw

\usepackage{natbib}
\usepackage[margin=1in,bottom=.5in,includehead,includefoot]{geometry}
\usepackage{hyperref}
\usepackage{language}
\usepackage{alltt}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}

%% Now begin customising things. See the fancyhdr docs for more info.

\chead{}
\lhead[\sf \thepage]{\sf \leftmark}
\rhead[\sf \leftmark]{\sf \thepage}
\lfoot{}
\cfoot{Independent contrasts}
\rfoot{}

\newcounter{myenumi}
\newcommand{\saveenumi}{\setcounter{myenumi}{\value{enumi}}}
\newcommand{\reuseenumi}{\setcounter{enumi}{\value{myenumi}}}

\pagestyle{fancy}

\def\R{{\sf R}}
\def\Rstudio{{\sf RStudio}}
\def\RStudio{{\sf RStudio}}
\def\term#1{\textbf{#1}}
\def\tab#1{{\sf #1}}


\usepackage{relsize}

\newlength{\tempfmlength}
\newsavebox{\fmbox}
\newenvironment{fmpage}[1]
     {
   \medskip
   \setlength{\tempfmlength}{#1}
   \begin{lrbox}{\fmbox}
     \begin{minipage}{#1}
     \vspace*{.02\tempfmlength}
		 \hfill
	   \begin{minipage}{.95 \tempfmlength}}
		 {\end{minipage}\hfill
		 \vspace*{.015\tempfmlength}
		 \end{minipage}\end{lrbox}\fbox{\usebox{\fmbox}}
	 \medskip
	 }


\newenvironment{boxedText}[1][.98\textwidth]%
{%
\begin{center}
\begin{fmpage}{#1}
}%
{%
\end{fmpage}
\end{center}
}

\newenvironment{boxedTable}[2][tbp]%
{%
\begin{table}[#1]
  \refstepcounter{table}
  \begin{center}
\begin{fmpage}{.98\textwidth}
  \begin{center}
	\sf \large Box~\expandafter\thetable. #2
\end{center}
\medskip
}%
{%
\end{fmpage}
\end{center}
\end{table}		% need to do something about exercises that follow boxedTable
}


\newcommand{\cran}{\href{http://www.R-project.org/}{CRAN}}

\title{Phylogenetic Independent Contrasts in R}

\author{
Casey Dunn}

\date{\today}

<<echo=FALSE>>=
options(width=70)
@



\begin{document}


\maketitle
\tableofcontents

%\parindent=0pt


\SweaveOpts{
  	dev="pdf",
	fig.path="figures/",
	prompt=FALSE,   
	comment="#"    # turn off commenting of ouput (but perhaps we should not do this either
	}

<<setup,echo=FALSE,message=FALSE>>=
showOriginal=FALSE
showNew=TRUE
@ 

\section{Introduction}

This example analysis presents the basics phylogenetic independent contrasts 
\citep{Felsenstein:1985ua}.
It expands on the example presented at the R phylogenetics wiki 
(\url{http://www.r-phylo.org/wiki/HowTo/Phylogenetic_Independent_Contrasts}).

This analysis uses the programming language R.
In the past decade, a large community of phylogenetic 
biologists interested in character evolution have written many analysis tools 
in R. This set of tools provides a rich environment for the study of character 
evolution. 


\section{Getting oriented with R}

R, like python and many other languages, can be used interactively, where you 
enter a few commands at a time, or in batch mode, where a series of commands are 
placed in a file and executed all at once. We will use R interactively, and 
load R code that others have already written for phylogenetic analyses as we 
go.

There are already \emph{many} general introductions, tutorials, and quick-references 
for R. I therefore won't provide a background on R itself, we will dive right 
into some analyses.

There is detailed information on phylogenetic analysis with R at both 
\href{http://www.r-phylo.org/wiki/Main_Page}{the R phylo wiki} and the 
\href{http://cran.r-project.org/web/views/Phylogenetics.html}{CRAN task page for phylogenetics}.

For the analyses below, you will need to install the `ape` library in R.


\section{Getting set up and loading the data}

Copy the data files (`Geospiza.txt` and `Geospiza.nex`) to a directory on your 
computer. Open the R interface (which was installed alongside the rest of the 
R components) or open a terminal window and launch an interactive R session 
with the command `R`.

Now, change to the directory where your data files are:

<<eval=FALSE>>=
setwd('DATADIR')
@


Where `DATADIR` is the directory where you put the data files. The R command 
`setwd()` is much like the shell command `cd` - it controls your working 
directory.

Load the ape library, which has the functions we will use for phylogenetic 
independent contrasts:

<<>>=
library(ape)
@

Load and prepare the data:

<<eval=FALSE>>=
geodata<-read.table("Geospiza.txt")
geotree<-read.nexus("Geospiza.nex")
@

<<echo=FALSE>>=
geodata <- read.table("../Geospiza.txt")
geotree <- read.nexus("../Geospiza.nex")
@

We now need to remove a taxon in the tree that isn't in the data file.

<<>>=
geotree <- drop.tip(geotree, "olivacea")
@
    
Plot the tree:

<<>>=
plot(geotree)
@


And take a look at the character data:

<<>>=
geodata
@

Data are available for five different characters for all the taxa in the tree.
We'll look at two of these characters, wing length and tarsus length. Extract 
these columns as their own variables to simplify later commands:

<<>>=
wingL <- geodata$wingL
tarsusL <- geodata$tarsusL
names(wingL) <- row.names(geodata)
names(tarsusL) <- row.names(geodata)
@

We can now plot these data directly onto the tips of the tree:

<<>>=
plot( geotree, label.offset = 0.04 )
tiplabels( round(wingL, 2) )
@

<<>>=
plot( geotree, label.offset = 0.04 )
tiplabels( round(tarsusL, 2) )
@


\section{Calculating independent contrasts}

Calcualte the independent contrasts for each of the variables:

<<>>=
ContrastwingL <- pic(wingL, geotree)
ContrasttarsusL <- pic(tarsusL, geotree)
@

And plot them on the tree:

<<>>=
plot (geotree)
nodelabels( round(ContrastwingL, 3), adj = c(0, -0.5), frame="n" )
nodelabels( round(ContrasttarsusL, 3), adj = c(0, 1), frame="n" )
@




\section{Investigating the relationships between the variables}

<<>>=
RegressTarsusWing <- lm( ContrastwingL~ContrasttarsusL -1 )
summary.lm( RegressTarsusWing )
@


<<>>=
plot( ContrastwingL, ContrasttarsusL )
abline( RegressTarsusWing )
@


\section{What if we didn't consider the phylogeny?}


<<>>=
RegressTarsusWingNaive <- lm( wingL~tarsusL )
summary.lm( RegressTarsusWingNaive )
@


<<>>=
plot( wingL, tarsusL )
@





\section{How this document was made}
This document is a computable data report compiled directly from the data. 
To recreate this file from the data, you will need to install:

\begin{itemize}
  \item R (\url{http://www.r-project.org}). This document was generated with 
  version 2.15.2.
  \item The R package knitr (\url{http://yihui.name/knitr/}), which can be 
  installed from within R. This document was generated with version 0.9.
  \item pdflatex, which comes with LaTeX distributions 
  (\url{http://www.latex-project.org/ftp.html}). This document was generated 
  with version 3.1415926-2.4-1.40.13.
\end{itemize}

From within the knitr directory, launch R and run:

<<eval=FALSE>>=
library(knitr)
knit("independent_contrasts.Rnw")
quit()
@

This will generate a new tex file. To compile this tex file into a pdf 
file, run the following at the shell command line:

<<eval=FALSE, prompt=FALSE>>=
pdflatex independent_contrasts.tex
@

In addition to recreating this document as-is, you can directly edit and add to 
the analyses in the .Rnw source file. You can also copy the R source code from 
the .Rnw file.

\bibliographystyle{amnat}

\bibliography{references}


\end{document}
